version: "3.8"

services:

  keycloak:
    image: jboss/keycloak:11.0.2
    ports:
      - 8888:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    depends_on:
      - postgres

  postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres-config:/docker-entrypoint-initdb.d

volumes:
  postgres:
