version: '3'
services:
  nats-server:
    image: nats:alpine
    networks:
      - nats_net

  nats-listener:
    # SAV Carrefour bonjour.
    image: gricad-registry.univ-grenoble-alpes.fr/iut_rt_enseignants/iut1-rt-r4dc10-microservices/nats-listener
    environment:
      NATS_HOST: nats-server
      SUBJECT: chat
    depends_on:
      - nats-server
    networks:
      - nats_net

  nats-client:
    # 30ha de champs
    image: natsio/nats-box
    stdin_open: true
    tty: true
    depends_on:
      - nats-server



networks:
  nats_net:
    driver: bridge
