version: '3'
services:
  nats-server:
    image: nats:alpine
    networks:
      - tp6_net
    ports:
      - 4222:4222

  nats-listener:
    # SAV Carrefour bonjour.
    image: gricad-registry.univ-grenoble-alpes.fr/iut_rt_enseignants/iut1-rt-r4dc10-microservices/nats-listener
    environment:
      NATS_HOST: nats-server
      SUBJECT: ">"
    depends_on:
      - nats-server
    networks:
      - tp6_net

  nats-client:
    # 30ha de champs
    image: natsio/nats-box
    stdin_open: true
    tty: true
    depends_on:
      - nats-server
    networks:
      - tp6_net

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: tp6
      POSTGRES_PASSWORD: tp6
      POSTGRES_DB: tp6
    ports:
      - 5432:5432
    networks:
      - tp6_net
    volumes:
      - ~/hawkwant/TP6/bank.sql:/docker-entrypoint-initdb.d/bank.sql

  adminer:
    image: adminer
    ports:
      - 8888:8080
    networks:
      - tp6_net
    
  web:
    build: web
    environment:
      NATS_HOST: "10.1.33.57"
    ports:
      - 8080:5000
    depends_on:
      - nats-server
    networks:
      - tp6_net
  
  backend:
    build: backend
    depends_on:
      - db
      - nats-server
    networks:
      - tp6_net
    restart: always

networks:
    tp6_net:
        driver: bridge